:mod:`clap.common.exceptions`
=============================

.. py:module:: clap.common.exceptions


Module Contents
---------------

.. py:exception:: RepositoryError

   Bases: :class:`Exception`


.. py:exception:: TableAlreadyExists(table_name: str, *args, **kwargs)

   Bases: :class:`clap.common.exceptions.RepositoryError`

   .. method:: __str__(self)




.. py:exception:: ModuleError

   Bases: :class:`Exception`


.. py:exception:: ValueNotFound

   Bases: :class:`clap.common.exceptions.RepositoryError`


.. py:exception:: ClusterError

   Bases: :class:`Exception`


.. py:exception:: ClusterCreationError

   Bases: :class:`clap.common.exceptions.ClusterError`


.. py:exception:: ConfigurationError

   Bases: :class:`Exception`

   This exception is raised if any invalid value or type exists in configuration files
       


